### ISSUE TITLE
ToDo on Ch5

### ISSUE THREAD

**Issue by hdashnow** [elegant-scipy/elegant-scipy#58]
Just moving @jni's Ch5 wish list here since I'm about to merge the PR (#57) it's in and we don't want to forget :)

Here's my current wish list, which is rather nitpicky! We can leave this till polishing time, but in case you're feeling like fixing something last minute. =)
- [ ] Move one or more of @stefanv's example applications of sparse matrices to the very top, right after "Many real-world matrices are sparse, which means that most of their values are zero."
- [x] Introduce the code example at the start, to be in line with the other chapters. (I'm happy to tackle this one, it's kinda my specialty. =)
- [ ] improve the way we use thresholds to segment. Rather than producing new RAGs for each threshold, use the same initial RAG and remove edges one by one.
- [x] at least _mention_ the other sparse formats, e.g. CSC and LIL, and mention that one can read the `scipy.sparse` docs for help deciding which sparse format best fits their problem.
- [ ] think of ways to break up @jni's VI/entropy text, which is very long, with some Python code.
- [ ] make sure `np.nonzero` is properly introduced, either in this chapter or earlier ones.
- [ ] improve variable names. This includes `aseg` vs `auto_seg`, `gt` vs `gnd_truth`, and using capital letters for 2D matrices in the linear algebra code.
- [ ] Expand note about scipy's/np.matrix's overriding of `*`, discussing Python 3's `@` operator.
- [ ] **Added 16/12 by @jni**: Add an alternative to RAG building using COO matrix, as detailed [here](https://github.com/scikit-image/scikit-image/pull/1495#issuecomment-164832104).
- [ ] general polishing, of course.

![mrmin](https://cloud.githubusercontent.com/assets/45071/10530098/d7d573cc-7358-11e5-9e81-bf3d1081af17.jpg)

But, overall, I'm pretty happy to turn this in as-is as a draft, knowing that we will continue to polish it. I think we cover the fundamentals of `scipy.sparse` pretty well! Thank you, this was a great team effort! Yay us! =P
